title: CenAccess Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://chottiwatt.in.th
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: true
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Main Site
      category: Website
      description: ""
      partial: ""
    - name: Resume Site
      category: Website
    - name: CenAccess Site
      category: Website
    - name: Mail Server
      category: Core Infrastructure
    - name: Cloudflare DNS
      category: Core Infrastructure
    - name: Cloudflare Zerotrust
      category: Core Infrastructure
    - name: Microsoft Azure
      category: Core Infrastructure
    - name: Amazon AWS
      category: Core Infrastructure
    - name: Netlify
      category: Core Infrastructure
    - name: Render
      category: Core Infrastructure
    - name: ChatGPT API Site
      category: Services
    - name: OpenVPN CloudConnexa
      category: Services
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: black
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Website
      closed: false
      untitled: false
    - name: Core Infrastructure
    - name: Services
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
